version: '3.8'

services:
  backend:
    image: multiapp_pipeline-backend:latest
    deploy:
      replicas: 2  # Set the desired number of replicas for the backend service
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - frontend

  frontend:
    image: multiapp_pipeline-frontend:latest
    deploy:
      replicas: 2  # Set the desired number of replicas for the frontend service
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: overlay
