version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
